esphome:
  name: ape
  platform: ESP8266
  board: nodemcu
  # Use a local copy of ESPHome
  includes:
    - ape.h

# api:
  
# ota:


logger:  
  level: DEBUG

i2c:

custom_component:
- id: ape
  lambda: |-
    auto ape_component = new ArduinoPortExtender(i2ccomponent, 0x08);
    return {ape_component};

output:
- platform: custom
  type: binary
  lambda: |-
    return {ape_binary_output(ape, 7),
            ape_binary_output(ape, 6),
            ape_binary_output(ape, 5),
            ape_binary_output(ape, 4)};
  outputs:
    - id: custom_binary_0
    - id: custom_binary_1
    - id: custom_binary_2
    - id: custom_binary_3

light:
  - platform: binary
    id: light_8
    output: custom_binary_0
  - platform: binary
    id: light_9
    output: custom_binary_1

binary_sensor:
  - platform: status
    name: "Living Room Status"
  - platform: custom
    lambda: |-
      return {ape_binary_sensor(ape, 8), 
              ape_binary_sensor(ape, 9)};
    binary_sensors:
      - name: "Input8"
        on_state:
          then:
            - light.toggle: light_8
      - name: ape_input_9
        on_state:
          then:
            - light.toggle: light_9