esphome:
  name: eh_dor_sur
  platform: ESP8266
  board: nodemcu
  # Use a local copy of ESPHome
  includes:
    - ape.h

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

api:
  
ota:

i2c:

logger:  
  level: DEBUG

custom_component:
  - id: ape
    lambda: |-
      auto ape_component = new ArduinoPortExtender(i2ccomponent, 0x08);
      return {ape_component};

output:
- platform: custom
  type: binary
  lambda: |-
    return {ape_binary_output(ape, 7),
            ape_binary_output(ape, 6),
            ape_binary_output(ape, 5)};
  outputs:
    - id: gpio_relay_1
      inverted: true
    - id: gpio_relay_2
      inverted: true
    - id: gpio_relay_3
      inverted: true

light:
  - platform: binary
    id: luz_dormitorio_sur
    name: "Dormitorio Sur"
    output: gpio_relay_1
  - platform: binary
    id: luz_dormitorio_sur_cama_pared
    name: "Dormitorio Sur Cama Ventana"
    output: gpio_relay_2
  - platform: binary
    id: luz_dormitorio_sur_cama_ventana
    name: "Dormitorio Sur Cama Pared"
    output: gpio_relay_3


binary_sensor:
  - platform: status
    name: "Dormitorio Sur Status"
  - platform: custom
    lambda: |-
      return {ape_binary_sensor(ape, 2), // ribbon purple
              ape_binary_sensor(ape, 3), // ribbon white 
              ape_binary_sensor(ape, 8), // ribbon verde 
              ape_binary_sensor(ape, 1), 
              ape_binary_sensor(ape, 0), 
              ape_binary_sensor(ape, 9), //  "Cama Derecha, estaba en A4/A5"
              ape_binary_sensor(ape, 10), // "Cama Derecha"
              ape_binary_sensor(ape, 14)}; // ribbon red 
    binary_sensors:
      - name: "Switch Puerta 1"
        internal: true
        on_state:
          then:
            - light.toggle: luz_dormitorio_sur
      - name: "Switch puerta 2"
        internal: true
        on_state:
          then:
            - light.toggle: luz_dormitorio_sur_cama_ventana
      - name: "Switch puerta 3"
        internal: true
        on_state:
          then:
            - light.toggle: luz_dormitorio_sur_cama_pared
      - name: "Switch Cama Pared 1"
        internal: true
        on_state:
          then:
            - light.toggle: luz_dormitorio_sur_cama_pared
      - name: "Switch Cama Pared 2"
        internal: true
        on_state:
          then:
            - light.toggle: luz_dormitorio_sur
      - name: "Switch Cama Ventana 1"
        internal: true
        on_state:
          then:
            - light.toggle: luz_dormitorio_sur_cama_ventana
      - name: "Switch Cama Ventana 2"
        internal: true
        on_state:
          then:
            - light.toggle: luz_dormitorio_sur
      - name: "Ventana Dormitorio Sur"
        device_class: window

# Example configuration entry
remote_transmitter:
  pin: GPIO14
  carrier_duty_percent: 50%


# Individual switches
switch:
  - platform: remote_transmitter
    name: "DorSur 25 cool"
    raw:
      carrier_frequency: 38kHz
      # tcl turn on 25 cool
      data: [ 3000,-1650,500,-1050,500,-1050,500,-325,500,-325,500,-325,500,-1050,500,-325,500,-325,500,-1050,500,-1050,500,
      -325,500,-1050,500,-325,500,-325,500,-1050,500,-1050,500,-325,500,-1050,500,-1050,500,-325,500,-325,500,-1050,500,-325,500,
      -325,500,-1050,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,
      -325,500,-325,500,-325,500,-325,500,-325,500,-1050,500,-325,500,-325,500,-1050,500,-325,500,-325,500,-1050,500,-1050,500,-325,
      500,-325,500,-325,500,-325,500,-325,500,-325,500,-1050,500,-1050,500,-1050,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,
      500,-325,500,-325,500,-325,500,-325,500,-325,500,-1050,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,
      -325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,
      -325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-1050,500,-1050,500,-325,500,-325,500,-325,
      500,-325,500,-325,500,-1050,500,-100000]
  - platform: remote_transmitter
    name: "DorSur AC Off"
    raw:
      carrier_frequency: 38kHz
      # tcl turn on 25 cool
      data: [ 3000,-1650,500,-1050,500,-1050,500,-325,500,-325,500,-325,500,-1050,500,-325,500,-325,500,-1050,500,-1050,500,-325,500,-1050,500,-325,500,-325,500,-1050,500,-1050,500,-325,500,-1050,500,-1050,500,-325,500,-325,500,-1050,500,-325,500,-325,500,-1050,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-1050,500,-325,500,-325,500,-1050,500,-1050,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-1050,500,-1050,500,-1050,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-1050,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-325,500,-1050,500,-1050,500,-1050,500,-1050,500,-1050,500,-1050,500,-1050,500,-325,500,-100000 ]
  - platform: remote_transmitter
    name: "Hyundai TV Power"
    nec:
      address: 0xFD
      command: 0xC03F
  - platform: remote_transmitter
    name: "Hyundai TV YouTube"
    nec:
      address: 0xFD
      command: 0xBA45
  - platform: remote_transmitter
    name: "Hyundai TV Netflix"
    nec:
      address: 0xFD
      command: 0xC23D # 0x43
  - platform: remote_transmitter
    name: "Sound bar Off"
    nec:
      address: 0xFF
      command: 0xA25D # 0x45
  - platform: remote_transmitter
    name: "Sound bar Optical"
    nec:
      address: 0xFF
      command: 0x22DD # 0x44 
  - platform: remote_transmitter
    name: "Sound bar -"
    nec:
      address: 0xFF
      command: 0x52AD # 0x4A
  - platform: remote_transmitter
    name: "Sound bar +"
    nec:
      address: 0xFF
      command: 0x5AA5 #0x5A