esphome:
  name: eh_patio
  platform: ESP8266
  board: nodemcu
  includes:
    - ape.h

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

api:
  
ota:

i2c:
  id: i2ccomponent

logger:  
  level: DEBUG

custom_component:
  - id: ape
    lambda: |-
      auto ape_component = new ArduinoPortExtender(i2ccomponent, 0x08);
      return {ape_component};

output:
- platform: custom
  type: binary
  lambda: |-
    return {ape_binary_output(ape, 7),
            ape_binary_output(ape, 6),
            ape_binary_output(ape, 5),
            ape_binary_output(ape, 4)};
  outputs:
    - id: gpio_relay_1
      inverted: true
    - id: gpio_relay_2
      inverted: true
    - id: gpio_relay_3
      inverted: true
    - id: gpio_relay_4
      inverted: true

light:
  - platform: binary
    id: galeria
    name: "Galeria"
    output: gpio_relay_1
  - platform: binary
    id: patio_proyector_este
    name: "Patio Proyector Este"
    output: gpio_relay_2
  - platform: binary
    id: patio_proyector_oeste
    name: "Patio Proyector Oeste"
    output: gpio_relay_3

switch:
  - platform: output
    id: sirena
    name: "Sirena"
    output: gpio_relay_4
  - platform: restart
    name: "Patio Restart"

binary_sensor:
  - platform: status
    name: "Patio Status"
    on_press:
      then:
      - script.execute: api_just_connected

  - platform: custom
    lambda: |-
      return {ape_binary_sensor(ape, 8),
              ape_binary_sensor(ape, 9),
              ape_binary_sensor(ape, 10),
              ape_binary_sensor(ape, 0),
              ape_binary_sensor(ape, 13),
              ape_binary_sensor(ape, 12),
              ape_binary_sensor(ape, 11)};

    binary_sensors:  
      - name: "Puerta Frente"
        device_class: door
      - name: "Puerta Cocina"
        device_class: door
      - name: "Puerta Estudio"
        device_class: door
      - name: "Movimiento Galeria"
        device_class: motion
      - name: "Switch Galeria 1"
        internal: true
        # disable because is pin 13 and needs pull up resisor
        # on_state:
        #   then:
        #     - light.toggle: galeria
      - name: "Switch Galeria 2"
        on_state:
          then:
            - script.execute: toggle_proyectores
        internal: true
      - name: "Switch Galeria 3"
        internal: true
        on_state:
          then:
            - light.toggle: galeria
  - platform: homeassistant
    name: "Switch Galeria 2 from HA"
    entity_id: binary_sensor.switch_estudio_galeria_2
    on_state:
      then: 
        if: 
          condition: 
            not: 
              script.is_running: api_just_connected
          then:
            light.toggle: galeria
          else:
            logger.log: 'Not toggling galeria, api just connected'

  - platform: homeassistant
    name: "Switch Galeria 3 from HA"
    entity_id: binary_sensor.switch_estudio_galeria_3
    on_state:
      then: 
        if: 
          condition: 
            not: 
              script.is_running: api_just_connected
          then:
            script.execute: toggle_proyectores

script:
  - id: api_just_connected
    then:
      - delay: 40s
  - id: toggle_proyectores
    then:
      - light.toggle: patio_proyector_este
      - lambda: |-
          bool esteStatus;
          id(patio_proyector_este)->current_values_as_binary(&esteStatus);
          if (esteStatus)
          {
            ESP_LOGD("main", "Este switch %d, turning on", esteStatus);
            id(patio_proyector_oeste).turn_on().perform();
          }
          else
          {
            ESP_LOGD("main", "Este switch %d, turning off", esteStatus);
            id(patio_proyector_oeste).turn_off().perform();
          }

# sensor:
#   - platform: custom
#     lambda: |-
#       auto my_sensor = new LM35Sensor(get_ape(ape), 1);
#       App.register_component(my_sensor);
#       return {my_sensor};
#     sensors:
#       - name: "Temperatura Galeria"
#         id: temperature
#         unit_of_measurement: °C
#         accuracy_decimals: 1

###
# module info:
# Male Header: 
# DI3   |  DI4  |  DI8 |  A1   |  5V
# 12V   |  NC   |  NC  | GND   |  A0 

# Female Header
# GND  |  3.3V
# DI9  |  DI10
# DI13 |  DI11
# DI12 |  NC

