esphome:
  name: eh_planta_alta
  platform: ESP8266
  board: nodemcu
  includes:
    - ape.h
  on_loop:
    then:
      # set the common neutral wire relay for patio lights
      lambda: |- 
        bool binary1;
        bool binary2;
        id(luz_patio_oeste).current_values_as_binary(&binary1);
        id(luz_patio_este).current_values_as_binary(&binary2);
        if (binary1 || binary2)
          id(gpio_relay_5).turn_on();
        else
          id(gpio_relay_5).turn_off();

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

# Enable logging 
logger:
  baud_rate: 0 # disable log by hardware UART
  level: VERBOSE
  logs:
    i2c: DEBUG
    uart: DEBUG
    #sim800l: VERY_VERBOSE

# Enable Home Assistant API
api:
  services:
  - service: send_sms
    variables:
      param_recipient: string
      param_message: string
    then:
    # - lambda: |-
    #     id(sim800l1).send_sms(param_recipient, param_message);
    - sim800l.send_sms:
        id: sim800l1
        recipient: !lambda 'return param_recipient;'
        message: !lambda 'return param_message;'

ota:

i2c:
  id: i2ccomponent

uart:
  baud_rate: 9600
  tx_pin: TX
  rx_pin: RX

sim800l:
  id: sim800l1
  on_sms_received:
    - logger.log:
        format: "Received '%s' from %s"
        args: [ 'message.c_str()', 'sender.c_str()' ]
    - lambda: |-
        id(sms_sender).publish_state(sender);
        id(sms_message).publish_state(message);

text_sensor:
  - platform: template
    id: sms_sender
    name: "Sms Sender"
  - platform: template
    id: sms_message
    name: "Sms Message"

custom_component:
- id: ape # bornes verdes
  lambda: |-
    auto ape_component = new ArduinoPortExtender(i2ccomponent, 0x08);
    return {ape_component};
- id: ape2 # sim 800 side
  lambda: |-
    auto ape_component = new ArduinoPortExtender(i2ccomponent, 0x09);
    return {ape_component};


binary_sensor:
  - platform: status
    name: "Planta Alta Status"

  - platform: homeassistant
    name: "Switch Escalera 1 from HA"
    entity_id: binary_sensor.switch_escalera_1
    on_state:
      then: 
        - light.toggle: luz_escalera

  - platform: custom
    lambda: |-
      return {ape_binary_sensor(ape2, 6), 
              ape_binary_sensor(ape2, 8), 
              ape_binary_sensor(ape2, 4), 
              ape_binary_sensor(ape2, 7), 
              ape_binary_sensor(ape2, 3),
              ape_binary_sensor(ape2, 9), 
              ape_binary_sensor(ape2, 5), 
              ape_binary_sensor(ape2, 2), 
              ape_binary_sensor(ape2, 11)};
    binary_sensors:
      - name: "Switch Escalera 1"
        internal: true
        on_state:
          then:
            - light.toggle: luz_escalera
      - name: "Switch Escalera 2"
        internal: true
        on_state:
          then:
            - light.toggle: luz_hall_pa
      - name: "Switch Ante Baño 1"
        internal: true
        on_state:
          then:
            - light.toggle: luz_ante_banio_pa
      - name: "Switch Ante Baño 2"
        internal: true
        on_state:
          then:
            - light.toggle: luz_ante_banio_pa
      - name: "Switch Baño"
        internal: true
        on_state:
          then:
            - light.toggle: luz_banio_pa
      - name: "Movimiento Baño"
        device_class: motion
      - name: "Movimiento Hall"
        device_class: motion
      - name: "Ventana Baño"
        device_class: window
      - name: "Tanque Agua Arriba Lleno"
        on_release:
          then:
            - sim800l.send_sms:
                id: sim800l1
                recipient: '+5493624207774'
                message: Tanque vacio. Llenando...
              
output:
- platform: custom
  type: binary
  lambda: |- # LTR all relays
    return {ape_binary_output(ape, 2), // Baño
            ape_binary_output(ape, 3), // Escalera 
            ape_binary_output(ape, 4), // Ante Baño 
            ape_binary_output(ape, 5), // Hall
            ape_binary_output(ape, 10), // Comun Luz Patio
            ape_binary_output(ape, 11), // Luz Patio Este
            ape_binary_output(ape, 12), // Luz Patio Oeste
            ape_binary_output(ape, 6)};
  outputs:
  - id: gpio_relay_1
    inverted: true
  - id: gpio_relay_2
    inverted: true
  - id: gpio_relay_3
    inverted: true
  - id: gpio_relay_4
    inverted: true
  - id: gpio_relay_5
    inverted: true
  - id: gpio_relay_6
    inverted: true
  - id: gpio_relay_7
    inverted: true
  - id: gpio_relay_8
    inverted: true

light:
  - platform: binary
    id: luz_banio_pa
    name: "Luz baño Planta alta"
    output: gpio_relay_1
  - platform: binary
    id: luz_escalera
    name: "Luz Escalera"
    output: gpio_relay_2
  - platform: binary
    id: luz_ante_banio_pa
    name: "Luz Ante baño Planta alta"
    output: gpio_relay_3
  - platform: binary
    id: luz_hall_pa
    name: "Luz Hall Planta alta"
    output: gpio_relay_4

  - platform: binary
    id: luz_patio_este
    name: "Luz Patio Este"
    output: gpio_relay_6
  - platform: binary
    id: luz_patio_oeste
    name: "Luz Patio Oeste"
    output: gpio_relay_7
  

  
## MW / UW Marked Wire / Unmarked Wire

# MW - White 0V
# MW - Red +12V



# APE2 06 Ribbon 3 Black - # MW - Yellow - Int Escalera 1 
# APE2 08 Ribbon 3 Purple - # UW - White - Int Escalera 2
# APE2 04 Ribbon 3 Blue - # UW - Yellow - Int Ante Baño 1
# APE2 07 Ribbon 3 Green - # UW - Red - Int Ante Baño 2
# APE2 03 Ribbon 3 Yellow - # UW - Blue Int Baño
# APE2 09 Ribbon 3 White - # MW - Blue - PIR Baño
# APE2 05 Ribbon 3 Gray - # MW - Marron - PIR Hall
# APE2 02 Ribbon 3 Red - # UW - Marron - Alarma Ventana Hall
# APE2 12 Ribbon 3 Brown - 
# APE2 13 Ribbon 3 Orange 

# APE2 11 Ribbon 2 White - Tanque 1 - Azul
# APE2 10 Ribbon 2 Purple - Tanque 2 - Verde

# APE1 07 Ribbon 2 Green - Tanque 3 - Blanco Verde
# APE1 08 Ribbon 2 Orange - Tanque 4 - Naranja
# APE1 09 Ribbon 2 Brown - Tanque 5 - Blanco Naranja

# APE1 A0 Ribbon 1 Black - Tanque 6 - Marron
# APE1 A1 Ribbon 1 Purple - Tanque 7 - Blanco - Marron
# APE1 A2 Ribbon 1 Green
# APE1 13 Ribbon 1 White
