esphome:
  name: eh_planta_alta
  platform: ESP8266
  board: nodemcu
  includes:
    - ape.h

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

# Enable logging
logger:
  #level: VERY_VERBOSE

# Enable Home Assistant API
api:

ota:

i2c:
  id: i2ccomponent

custom_component:
- id: ape
  lambda: |-
    auto ape_component = new ArduinoPortExtender(i2ccomponent, 0x08);
    return {ape_component};

output:
- platform: custom
  type: binary
  lambda: |-
    return {ape_binary_output(ape, 7),
            ape_binary_output(ape, 6),
            ape_binary_output(ape, 5),
            ape_binary_output(ape, 4)};
  outputs:
    - id: gpio_relay_1
      inverted: true
    - id: gpio_relay_2
      inverted: true
    - id: gpio_relay_3
      inverted: true
    - id: gpio_relay_4
      inverted: true

light:
  - platform: binary
    id: luz_escalera
    name: "Luz Escalera"
    output: gpio_relay_1
  - platform: binary
    id: luz_hall_pa
    name: "Luz Hall Planta alta"
    output: gpio_relay_2
  - platform: binary
    id: luz_ante_banio_pa
    name: "Luz Ante baño Planta alta"
    output: gpio_relay_3
  - platform: binary
    id: luz_banio_pa
    name: "Luz baño Planta alta"
    output: gpio_relay_4

binary_sensor:
  
  - platform: status
    name: "Planta Alta Status"