esphome:
  name: test_local2
  platform: ESP8266
  board: nodemcu
  platformio_options:
    upload_speed: 921600

  on_boot:
    - lambda: |-
        id(lsx).play("lala");

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  fast_connect: true
  manual_ip:
    static_ip: 10.0.1.199
    gateway: 10.0.1.1
    subnet: 255.0.0.0


logger:
  level: VERBOSE

output:
  - platform: esp8266_pwm
    pin: D1
    frequency: 1000 Hz
    id: pwm_output


api:

rtttl:
  id: lsx
  output: pwm_output
