esphome:
  name: uptime_test
  platform: ESP8266
  board: nodemcuv2
  platformio_options:
    upload_speed: 921600

logger:
  level: VERY_VERBOSE

sensor:
  - platform: dht
    pin: D5
    update_interval: 60s
    temperature:
      name: "Living Room Temperature"
    humidity:
      name: "Living Room Humidity"
