esphome:
  name: test_local
  platform: ESP8266
  board: nodemcu
  includes:
    - ape.h

logger:
  level: VERY_VERBOSE
  logs:
    i2c: VERBOSE

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass
  
api:
  
ota:

sensor:
  - platform: dht
    pin: D4
    model: DHT22
    temperature:
      name: "Estudio Test Temperature"
      id: estudio_test_dht_temp
    humidity:
      name: "Estudio Test Humidity"
    update_interval: 5s

i2c:
  id: i2c_component

custom_component:
- id: ape
  lambda: |-
    auto ape_component = new ArduinoPortExtender(id(i2c_component), 0x08);
    return {ape_component};

output:
- platform: custom
  type: binary
  lambda: |-
    return {ape_binary_output(id(ape), 13)};
  outputs:
    - id: arduino_led_13

light:
  - platform: binary
    id: luz_led_test_arduino
    name: Arduino Led 13
    output: arduino_led_13

binary_sensor:
- platform: custom
  lambda: |-
    return {ape_binary_sensor(id(ape), 9)};

  binary_sensors:
  - name: "Switch Test 1" 
- platform: homeassistant
  name: "Switch Este Test 1 from HA"
  entity_id: binary_sensor.switch_este_test_1
  on_state:
    then: 
      - light.toggle: luz_led_test_arduino


switch:
  - platform: restart
    name: "Test Restart"
