esphome:
  name: test_local
  platform: ESP8266
  board: nodemcu
  platformio_options:
    upload_speed: 921600
  includes:
    - ape.h

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

api:

ota:

i2c:
  id: i2ccomponent

logger:
  level: DEBUG
  esp8266_store_log_strings_in_flash: False


custom_component:
  - id: ape
    lambda: |-
      auto ape_component = new ArduinoPortExtender(i2ccomponent, 0x08, true);
      return {ape_component};

output:
- platform: custom
  type: binary
  lambda: |-
    return {ape_binary_output(ape, 3),
            ape_binary_output(ape, 4)};
  outputs:
    - id: output_pin_3
      inverted: true
    - id: output_pin_4
      inverted: true

switch:
  - platform: output
    name: Switch pin 3
    output: output_pin_3

light:
  - platform: binary
    name: Switch pin 4
    output: output_pin_4

sensor:
  - platform: custom
    lambda: |-
      return {ape_analog_input(ape, 1),  // 1 = A1
              ape_analog_input(ape, 2)};
    sensors:
      - name: Analog A1
        id: analog_a1
        filters:
          - throttle: 1s
      - name: Analog A2
        id: analog_a2
        filters:
          - throttle: 2sec


binary_sensor:
  - platform: custom
    lambda: |-
      return {ape_binary_sensor(ape, 14), // 14 = A0
              ape_binary_sensor(ape, 9)};

    binary_sensors:
      - id: binary_sensor_pin2
        name: Binary sensor pin 2
      - id: binary_sensor_pin3
        name: Binary sensor pin 3


interval:
  - interval: 1 seconds
    then:
      lambda: |-
        ESP_LOGI("main", "Analog sensor: %f", ((id(analog_a1).state / 1023.0 * 3.3) * 12.95) / 2.3258);

