esphome:
  name: test_local
  platform: ESP8266
  board: nodemcu
  platformio_options:
    upload_speed: 921600
  includes:
    - aczc.h

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

api:

ota:

logger:
  level: VERBOSE

remote_transmitter:
  carrier_duty_percent: 50%
  pin: D5

sensor:
  - platform: dht
    pin: D2
    model: DHT22
    temperature:
      name: "Estudio Test Temperature"
      id: estudio_test_dht_temp
    humidity:
      name: "Estudio Test Humidity"
    update_interval: 600s


climate:
  - platform: mitsubishi
    name: mitsubishi ac
    sensor: estudio_test_dht_temp