esphome:
  name: test_local
  platform: ESP8266
  board: nodemcu
  platformio_options:
    upload_speed: 921600
  includes:
    - aczc.h

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

api:

ota:

logger:
  level: VERBOSE

remote_transmitter:
  carrier_duty_percent: 50%
  pin: D5

climate:
  - platform: whirlpool
    name: whirlpool ac

binary_sensor:
  - platform: gpio
    name: test
    pin:
      number: D1
      mode: INPUT_PULLUP
    filters:
      - invert:
