esphome:
  name: eh_coolix_estudio
  platform: ESP8266
  board: nodemcu

logger:
  level: VERBOSE

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

api:

ota:

dallas:
  pin: D4
  update_interval: 60s

sensor:
  - platform: dallas
    address: 0xF176C32712646128
    id: dallas_temp
    internal: true

remote_receiver:
  id: rcvr
  pin:
    number: D5
    inverted: True
    mode: INPUT_PULLUP
  tolerance: 55
  dump: raw

remote_transmitter:
  carrier_duty_percent: 50%
  pin: D6

climate:
  - platform: coolix
    receiver_id: rcvr
    sensor: dallas_temp
    name: AC