esphome:
  name: test_esp32
  platform: ESP32
  board: nodemcu-32s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  # ap:
  #   ssid: "Test Esp32 Fallback Hotspot"
  #   password: "HBPaN3WZOE38"

# captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:

output:
  - platform: ledc
    pin: GPIO19
    id: 'buzzer'

switch:
  - platform: template
    name: buzzzzzz
    turn_on_action:
      then:
        - output.ledc.set_frequency:
            id: buzzer
            frequency: 800Hz
        - output.set_level:
            id: buzzer
            level: 50%
        - delay: 500ms
        - output.turn_off: buzzer
        - delay: 200ms
        - output.ledc.set_frequency:
            id: buzzer
            frequency: 600Hz
        - output.set_level:
            id: buzzer
            level: 50%
        - delay: 500ms
        - output.turn_off: buzzer