esphome:
  name: test_local
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_pass

# Enable logging
logger:
  level: VERBOSE

# Enable Home Assistant API
api:

ota:

uart:
#  id: sim800uart
  tx_pin: D0
  rx_pin: D1
  baud_rate: 9600

sim800l:
#  uart_id: sim800uart
  id: sms
  on_sms_received:
    lambda: |-
      ESP_LOGD("main", "Received sms from %s: %s", sender.c_str(), message.c_str());
      id(received_sms_from).publish_state(sender);
      id(received_sms_body).publish_state(message);

binary_sensor:
  platform: gpio
  name: "Send sms"
  pin: D8
  on_press:
    lambda: |-
      id(sms).send_sms("+5493624207774", "Hello there from ESPHome");

text_sensor:
  - platform: template
    id: received_sms_from
  - platform: template
    id: received_sms_body


font:
  - file: "Roboto-Regular.ttf"
    id: my_font
    size: 14

i2c:
  sda: D3
  scl: D4

display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    reset_pin: D0
    address: 0x3C
    lambda: |-
      it.print(0, 0, id(my_font), id(received_sms_from).state.c_str());
      it.print(0, 14, id(my_font), id(received_sms_body).state.c_str());

      
remote_transmitter:
  carrier_duty_percent: 50%
  pin: D5

climate:
  platform: tcl112
  name: 'test AC TCL'